using System;
using Content.Client.Audio;
using Content.Client.UI;
using Content.Shared.ContentCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client.MainMenu;

[GenerateTypedNameReferences]
public sealed partial class MainMenuHud : Control
{
	[Dependency] private readonly MainMenuAudio _audio = default!;

	public MainMenuHud()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);

		CustomCursor.SetCursor(this);
		_audio.AddButtonSound("pop.wav", 
			ConnectToLocalHostButton,
			ConnectButton,
			OptionsButton,
			QuitButton);

		var sprite = new SpriteSpecifier.Rsi(new("/Textures/Interface/idle.rsi"), "idle");
		IdleAnimation.SetFromSpriteSpecifier(sprite);
	}
}