using System;
using Content.Client.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MainMenu;

[GenerateTypedNameReferences]
public sealed partial class MainMenuHud : Control
{
	public MainMenuHud()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);

		CustomCursor.SetCursor(this);
	}

	public string Username
    {
        get => UsernameLineEdit.Text;
        set => UsernameLineEdit.Text = value;
    }

    public string Address
    {
        get => AddressLineEdit.Text;
        set => AddressLineEdit.Text = value;
    }
}