using System;
using Content.Client.Audio;
using Content.Client.UI;
using Content.Shared.ContentCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.MainMenu;

[GenerateTypedNameReferences]
public sealed partial class MainMenuHud : Control
{
	[Dependency] private readonly MainMenuAudio _audio = default!;

	public MainMenuHud()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);

		CustomCursor.SetCursor(this);
		_audio.AddButtonSound("pop.wav", 
			ConnectToLocalHostButton,
			ConnectButton,
			OptionsButton,
			QuitButton);
	}

	public string Username
    {
        get => UsernameLineEdit.Text;
        set => UsernameLineEdit.Text = value;
    }

    public string Address
    {
        get => AddressLineEdit.Text;
        set => AddressLineEdit.Text = value;
    }
}