using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class IdleAnimation : Control
{
	private const string Rsi = "/Textures/Interface/idle.rsi";
	private const string State = "idle";

	public IdleAnimation()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);

		var sprite = new SpriteSpecifier.Rsi(new(Rsi), State);
		AnimatedTexture.SetFromSpriteSpecifier(sprite);
	}
}