using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.Mapping
{
	[GenerateTypedNameReferences]
	public sealed partial class MappingWindow : DefaultWindow
	{
		public MappingWindow()
		{
			RobustXamlLoader.Load(this);
			Tabs.SetTabTitle(0, "Entities");
			Tabs.SetTabTitle(1, "Tiles");
			Tabs.SetTabTitle(2, "Commands");
		}
	}
}
