using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.EscapeMenu
{
	[GenerateTypedNameReferences]
	public sealed partial class MappingWindow : DefaultWindow
	{

	}
}
