using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.InGame;

[GenerateTypedNameReferences]
public sealed partial class InGameHUDScreen : UIScreen
{
	[Dependency] private readonly IGameTiming _gameTiming = default!;

	public InGameHUDScreen()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);
		FpsBox.AddChild(new FpsCounter(_gameTiming));
	}
}
