using Content.Client.UI;
using Content.Shared.ContentCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Network;
using Robust.Shared.Timing;

namespace Content.Client.InGame;

[GenerateTypedNameReferences]
public sealed partial class InGameHUDScreen : UIScreen
{
	[Dependency] private readonly IGameTiming _gameTiming = default!;
	[Dependency] private readonly IEyeManager _eyeManager = default!;
	[Dependency] private readonly IConfigurationManager _configurationManager = default!;
	[Dependency] private readonly IClientNetManager _netManager = default!;

	public InGameHUDScreen()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);

		var viewport = new MainViewportContainer(_eyeManager);
		CustomCursor.SetCursor(viewport);
		_eyeManager.MainViewport = viewport;
		ViewportBox.AddChild(viewport);
		SetAnchorPreset(ViewportBox, LayoutPreset.Wide);
		SetAnchorPreset(viewport, LayoutPreset.Wide);

		FpsBox.AddChild(new FpsCounter(_gameTiming));
		FpsBox.Visible = _configurationManager.GetCVar(ContentCVars.HudFpsVisible);
		_configurationManager.OnValueChanged(ContentCVars.HudFpsVisible, (visible) => 
		{ 
			FpsBox.Visible = visible;
		});
		PingLabel.Visible = _configurationManager.GetCVar(ContentCVars.HudPingVisible);
		_configurationManager.OnValueChanged(ContentCVars.HudPingVisible, (visible) =>
		{
			PingLabel.Visible = visible;
		});
	}

	protected override void FrameUpdate(FrameEventArgs args)
	{
		base.FrameUpdate(args);
		PingLabel.Text = $"Ping: {_netManager.ServerChannel?.Ping.ToString() ?? "Not Connected" }";
	}
}
