using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.InGame;

[GenerateTypedNameReferences]
public sealed partial class InGameHUDScreen : UIScreen
{
	[Dependency] private readonly IGameTiming _gameTiming = default!;
	[Dependency] private readonly IEyeManager _eyeManager = default!;

	public InGameHUDScreen()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);

		var viewport = new MainViewportContainer(_eyeManager);
		//viewport.DefaultCursorShape = CursorShape.Crosshair;
		ViewportBox.AddChild(viewport);
		SetAnchorPreset(ViewportBox, LayoutPreset.Wide);
		SetAnchorPreset(viewport, LayoutPreset.Wide);

		FpsBox.AddChild(new FpsCounter(_gameTiming));
	}
}
