using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Test;

[GenerateTypedNameReferences]
public sealed partial class TestWindow : Control
{
    public string Label
    {
        get => TestButton.Text ?? "";
    }
}