using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.OptionsMenu
{
	[GenerateTypedNameReferences]
	public sealed partial class HotkeyTab : Control
	{
		public HotkeyTab()
		{
			RobustXamlLoader.Load(this);
			IoCManager.InjectDependencies(this);
		}
	}
}
