using Content.Client.UI;
using Content.Client.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.OptionsMenu
{
	[GenerateTypedNameReferences]
	public sealed partial class OptionsMenu : ContentWindow
	{
		public OptionsMenu()
		{
			RobustXamlLoader.Load(this);
			IoCManager.InjectDependencies(this);

			CustomCursor.SetCursor(this);

			Tabs.SetTabTitle(0, "Graphics");
			Tabs.SetTabTitle(1, "Audio");
			Tabs.SetTabTitle(2, "Hotkeys");

			OnClose += () =>
			{
				Graphics.OnClosed();
				Audio.OnClosed();
			};
		}
	}
}
