using Content.Client.Audio;
using Content.Client.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.EscapeMenu
{
	[GenerateTypedNameReferences]
	public sealed partial class EscapeMenu : DefaultWindow
	{
		[Dependency] private readonly MainMenuAudio _audio = default!;

		public EscapeMenu()
		{
			RobustXamlLoader.Load(this);
			IoCManager.InjectDependencies(this);

			AudioHelpers.AddButtonSound("pop.wav", new List<BaseButton>
			{
				OptionsButton,
				DisconnectButton
			});

			CustomCursor.SetCursor(this);
		}
	}
}
