using Content.Shared.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyHud : Control
{
	public LobbyHud()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);		
	}

	public void SetState(LobbyUiState state)
	{

	}
}