using Content.Client.Audio;
using Content.Client.UI;
using Content.Shared.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyHud : Control
{
	[Dependency] private readonly MainMenuAudio _audio = default!;

	public LobbyHud()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);

		AudioHelpers.AddButtonSound("pop.wav", new List<BaseButton>
		{
			StartGameButton,
			StartMappingButton,
			OptionsButton,
			DisconnectButton
		});

		CustomCursor.SetCursor(this);
	}

	public void SetState(LobbyUiState state)
	{

	}
}