using Content.Client.UI;
using Robust.Client;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.AczLauncherConnecting
{
	[GenerateTypedNameReferences]
	public sealed partial class AczLauncher : Control
	{
		[Dependency] private readonly IGameController _gameController = default!;

		public AczLauncher()
		{
			RobustXamlLoader.Load(this);
			IoCManager.InjectDependencies(this);

			CustomCursor.SetCursor(this);

			LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

			QuitButton.OnPressed += _ =>
			{
				_gameController.Shutdown("Client pressed quit button.");
			};
		}
	}
}
